# Generated by Django 4.0.6 on 2022-08-01 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('room_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conferenceroom',
            name='room_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.CreateModel(
            name='RoomReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('comment', models.TextField(null=True)),
                ('room_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_app.conferenceroom')),
            ],
        ),
    ]
